### ISSUE TITLE
BreadCrumbs 좋은 구조 고민하기 

### ISSUE THREAD

**Issue by yooyouny** [Siren-repo/Notion_Breadcrumbs#3]
### 요구사항
페이지 정보 조회 API: 특정 페이지의 정보를 조회할 수 있는 API를 구현하세요.

- 입력: 페이지 ID
- 출력: 페이지 제목, 컨텐츠, 서브 페이지 리스트, **브로드 크럼스 ( 페이지 1 > 페이지 3 > 페이지 5)**
- 컨텐츠 내에서 서브페이지 위치 고려 X

### 고민해야할 내용 
1. 테이블 구조 고민하기
2. BreadCumbs를 찾는 로직 고민하기 

해당 사항에 대해 고민해봅시다 😀

**Comment by yooyouny** [comment]
일단 지금 PR 올라온 주호님이랑 제 코드에서 브레드크럼즈 찾는 로직을 보면, 
주호님은 id로 Page를 찾고 while문 안에서 parentId를 찾아 parentId == null일 때까지 찾는 방식이고 
저는 id를 받아서 재귀쿼리로 한번에 찾아오는 차이 인 것 같아요

**Comment by HSBODo** [comment]
저도 주호님과 같이 while문으로 브로드크럼즈를 찾는 로직인데 유연님 처럼 재귀쿼리를 사용 하는 것은 생각지도 못했네요 
혹시 DB단에서의 재귀쿼리와 application단의 반복문 두개의 속도와 부하면에서 어느것이 이점이 더 클까요?

**Comment by Ho-Tea** [comment]
재귀쿼리를 잘안써봐서 찾아봤는데 계층형구조에  잘맞는거같습니다! 테이블구조는 저랑 큰차이는 잘 안보여서 재귀쿼리로 구현한 유연님 코드로 제출하는게 괜찮아 보입니다

**Comment by yooyouny** [comment]
> 저도 주호님과 같이 while문으로 브로드크럼즈를 찾는 로직인데 유연님 처럼 재귀쿼리를 사용 하는 것은 생각지도 못했네요 혹시 DB단에서의 재귀쿼리와 application단의 반복문 두개의 속도와 부하면에서 어느것이 이점이 더 클까요?

음.. 재귀쿼리는 jdbcTemple.query를 한번만 호출하지만 반복문 안에서 쿼리를 여러번 호출하면 아무래도 서버와의 통신횟수가 많아지니까 추가적인 네트워크 지연이나 부하가 생길 수도 있을것 같습니다.
